---
title: "Milestone 1.3"
author: "Laura Diekmann"
date: "2 6 2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
library(readr)
library(dplyr)
library(plyr)
library(ggplot2)
library(ggcorrplot)
library(devtools)


```

```{r}
## creating a data frame df_treat consisting of dosage and broadID
dosage<- prism.treat$dose
broadID<- prism.treat$broad_id

df_treat <- data.frame(broadID, dosage)
df_treat
```

```{r}
##creating a dataframe df_treat2 consisting the dosage and broadID2

broadID2<- prism.treat[,0]
broadID2
broadID3<-rownames(prism.treat)

df_treat2<- data.frame (broadID2, dosage)
df_treat2


```

```{r}
##We employed a 2-stage screening strategy whereby drugs were first screened in triplicate at a single dose (2.5 μM). 1,448 screening positives were then re-screened in triplicate in an 8-point dose-response ranging from 10 μM to 600 pM

## only the low dosages < 2.5 μM
df_treat_lowdose<-df_treat[dosage<2.5, c("broadID","dosage")]
df_treat_lowdose

#### wie mache ich das mit dem broadID2?

##only the high dosages > 2.5μM
df_treat_highdose<-df_treat[dosage>=2.5, c("broadID","dosage")]
df_treat_highdose









```


```{r}
## copied from Versuch1

## creating a data frame df_cl consisting of DepMap_IDs and lineages
lineage <- prism.cl$lineage
DepMap_ID <- prism.cl$DepMap_ID 

df_cl <- data.frame(DepMap_ID, lineage)

## subsetting data frame to obtain only ovary cell lines with their DepMap_IDs

df_ovary_cl <- subset(df_cl, lineage == "ovary")

df_ovary_cl

dim(df_ovary_cl)

## creating a vector that only contains the ovary cancer DepMap_IDs 

vector_ovary_DepMI <- as.vector(df_ovary_cl$DepMap_ID)


vector_ovary_DepMI

df_ovary_DepMI_prism  <- prism[rownames(prism) %in% vector_ovary_DepMI,]

df_ovary_DepMI_prism


```
```{r, dataframe dose and ovary cell lines}
## creating a dataframe with the ovary DepMap_IDs their ploriferation values and the dose

new_df_ovary_DepMI_prism<- as.data.frame(t(df_ovary_DepMI_prism))
new_df_ovary_DepMI_prism


##creating a dataframe from the ovary cell lines with DepMApID,ploriferation values, broad ID und dose

df_ovary_DepMI_prism_treat <-merge(prism.treat,new_df_ovary_DepMI_prism , by="row.names")
df_ovary_DepMI_prism_treat

##deleting all other columns 
df_ovary_DepMI_prism_treat[,c('screen_id','compound_plate','moa','target','disease.area','indication','smiles','phase')]<-list(NULL)

##deleting NAs
df_ovary_DepMI_prism_treat_NAs<-drop_na(df_ovary_DepMI_prism_treat)
df_ovary_DepMI_prism_treat_NAs


df_ovary_DepMI_prism_treat


```
```{r}

## the most effective drugs in a vector
most_effective_moas_drugs2<-c("TAS-103","nemorubicin","idarubicin","10-hydroxycamptothecin", "amsacrine","SN-38","doxorubicin","exatecan-mesylate","genz-644282","ixazomib-citrate","carfilzomib","delanzomib","ixazomib","BGT226","buparlisib","CUDC-907","PCI-24781","AR-42", "givinostat","scriptaid","M-344","romidepsin","trichostatin-a","vorinostat","JNJ-26481585","pelitinib","PD-168393","dacomitinib","afatinib","AT-7519","dinaciclib","CR8-(R)","P276-00" ,"R547","oridonin","obatoclax","HA14-1","TW-37","digoxin","thonzonium","digitoxigenin","NMS-873")

##df_ovary_DepMI-prism_treat reduced to only the effective drugs out of Milestone 1.1, 1.2
df_ovary_prism_treat_effective <- df_ovary_DepMI_prism_treat[df_ovary_DepMI_prism_treat$name %in% most_effective_moas_drugs2,]

df_ovary_prism_treat_effective
```


```{r}
##creating a dataframe wit only low dosages 
df_lowdose<- df_ovary_DepMI_prism_treat[-which(df_ovary_DepMI_prism_treat$dose>2,5),]
df_lowdose
##without NAs
df_lowdose_NAs<-df_ovary_DepMI_prism_treat_NAs[-which(df_ovary_DepMI_prism_treat_NAs$dose>2,5),]
df_lowdose_NAs

##creating a dataframe wit only high dosages 
df_highdose<- df_ovary_DepMI_prism_treat[-which(df_ovary_DepMI_prism_treat$dose<=2,5),]
df_highdose
##without NAs
df_highdose_NAs<-df_ovary_DepMI_prism_treat_NAs[-which(df_ovary_DepMI_prism_treat_NAs$dose<=2,5),]
df_highdose_NAs

##repeating this with the most effective dataframe df_ovary_prism_treat_effective

##creating a dataframe wit only low dosages 
df_lowdose_effectivedrugs<- df_ovary_prism_treat_effective[-which(df_ovary_prism_treat_effective$dose>2,5),]
df_lowdose_effectivedrugs


##creating a dataframe wit only high dosages 
df_highdose_effectivedrugs<- df_ovary_prism_treat_effective[-which(df_ovary_prism_treat_effective$dose<=2,5),]
df_highdose_effectivedrugs
```


```{r}
##using pivot_longer to do a long dataframe
df_ovary_prism_treat_effective_long<-pivot_longer(df_ovary_prism_treat_effective,cols = starts_with("ACH"),names_to= "DepMap_ID", values_to="proliferationvalues", values_drop_na=TRUE)
## making a ggplot out of the long dataframe
ggplot_dose_proliferationvalues<-ggplot(df_ovary_prism_treat_effective_long, aes(x=dose, y=proliferationvalues)) +
  geom_point()+
  labs(title="Plot of proliferation value per dose",x="Dose (µm)", y = "proliferation value")
ggplot_dose_proliferationvalues

factor_high_low<- as.factor(c("2,5<10","2,5","0<2,5"))
df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$dose>2,5]= factor_high_low[1]
df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$dose==2,5]= factor_high_low[2]
df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$dose<2,5]= factor_high_low[3]

df_ovary_prism_treat_effective_long

ggplot_dose_proliferationvalues2<-ggplot(df_ovary_prism_treat_effective_long, aes(x=dose, y=proliferationvalues, group= DepMap_ID)) +
  geom_boxplot(aes(fill=DepMap_ID))+
  labs(title="Plot of proliferation value per dose",x="Dose (µm)", y = "proliferation value")

ggplot_dose_proliferationvalues2
```


```{r}
## pearson correlation between the proliferation value and dose, to test the independence of the proliferation value from the dosis

cordf_effective= data.frame(row.names=rownames(prism))

for (drug in unique(df_ovary_prism_treat_effective$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  cordf_effective[drug]=apply(response,1,function(x){cor(x,dose)})
}
cordf_effective<-cordf_effective[rownames(cordf_effective) %in% vector_ovary_DepMI,]
cordf_effective
####Der Korrelationskoeffizient nach Person liegt stets zwischen eins und minus eins, wobei eins einen perfekt positiven und minus eins eine perfekt negative Korrelation impliziert. Man schreibt also:

####r\ \in\left[-1;+1\right]

####Es gibt also verschiedene Szenarien, auf die wir hier eingehen.

####r\approx0 : Erhältst du ein Ergebnis von ungefähr null sind die Variablen unkorreliert.
####Das heißt, zwischen ihnen besteht kein linearer Zusammenhang. Ein Beispiel hierfür wäre wenn man versucht einen Zusammenhang zwischen und Autokennzeichen und Körpergröße zu finden.
 

####r\ >\ 0 : Ist der Wert von r größer als 0, dann nennt man das eine positive Korrelation. Das bedeutet, dass größere Werte von X auch mit größeren Werten von Y einher gehen. Hier könnte man den Zusammenhang zwischen der Körpergröße eines Menschen und der Schuhgröße dieser Person hernehmen.
 

####r\ <\ 0 :  Zuletzt betrachten wir noch den Fall, dass der Wert von r kleiner als Null ist, es sich also um einen negativen Zusammenhang handelt. Anders als bei der positiven Korrelation fallen hier die Werte von Y mit steigenden X-Werten. Hier könnte man sagen, dass je mehr Kilometer man mit dem Auto zurücklegt, desto weniger Benzin ist im Tank.

```
```{r}
cormatrix_effective<- data.matrix(cordf_effective)
cormatrix_effective
dim(cormatrix_effective)

##visualization the correlation using ggplot2
ggplot2_dose_proliferation<-ggcorrplot(cormatrix_effective)
ggplot2_dose_proliferation

hist(cormatrix_effective, xlab="Pearson Correlationvalues",main= paste("Pearson Correlation Histogram"))

```
```{r}
##scatter plot of Ovary cell line proliferation value on the y-achsis and dosis of the different drugs on the x-achsis

scatter_plot_dose_proliferation<-plot(df_ovary_prism_treat_effective$dose,df_ovary_prism_treat_effective$`ACH-000013`,col="blue",xlab="Dosis of the different drugs", ylab="Ovary cellline proliferation value")

for (i in 6:34){
  i
  points(x=df_ovary_prism_treat_effective$dose,df_ovary_prism_treat_effective[,i], col="blue")
  for(i in 5:34){
    i
    abline(lm(df_ovary_prism_treat_effective$dose~df_ovary_prism_treat_effective[,i]))
  }
}

```


