---
title: "Untitled"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}
load("/Users/caro/Desktop/Uni_Heidelberg/SoSe21/Data_Project/original_data_environment.RData")
```


```{r c1 - data exploration and organization - reducing data set to obtain ovary cancer values}

## Creating a data frame df_cl consisting of all DepMap_IDs and the different cell line lineages.

lineage <- prism.cl$lineage
DepMap_ID <- prism.cl$DepMap_ID

df_cl <- data.frame(DepMap_ID, lineage)

## subsetting data frame to obtain only ovary cell lines with their DepMap_IDs

df_ovary_cl <- subset(df_cl, lineage == "ovary")

df_ovary_cl

dim(df_ovary_cl)

## creating a vector that only contains the ovary cancer DepMap_IDs

vector_ovary_DepMI <- as.vector(df_ovary_cl$DepMap_ID)

vector_ovary_DepMI
```


```{r c2  - data exploration and organization - creating the ovary subset of prism}

## creating a subset dataframe of prism with only the ovary DepMap_IDs and their proliferation values   

vector_ovary_DepMI

df_ovary_DepMI_prism  <- prism[rownames(prism) %in% vector_ovary_DepMI,]

df_ovary_DepMI_prism
```


```{r c3 - data exploration and organization -  histograms of prism data set focusing only on ovary cell lines}

## computing histograms of distribution of mean sensitivity across all ovary cell lines and all drugs

hist_cell_growth_cl  <- hist(apply(df_ovary_DepMI_prism, 1,function(x){mean(x,na.rm=TRUE)}), breaks = 50, xlim = c(-0.9, 0),  main = "Ovary Cell lines", xlab = "Mean log fold-change in cell growth")

hist_cell_growth_drugs <- hist(apply(df_ovary_DepMI_prism, 2,function(x){mean(x,na.rm=TRUE)}), breaks = 50, main = "Drugs", xlab = "Mean log fold-change in cell growth")

hist_cell_growth_cl
hist_cell_growth_drugs
```

```{r c4 - data exploration and organization - changing our dataframe in order to be able to find the most effective drugs}

## creating data.frame that contains the most effective treatment values for each drug and dosage (min values) for every cell line

prism_reduced = data.frame(row.names = rownames(prism))

for (i in 1:(ncol(prism)/8)){
  prism_subset = prism[,(8*(i-1)+1):(8*i)]
  max_effect = apply(prism_subset, 1, min)
  drug = toString(prism.treat$name[which(rownames(prism.treat)== colnames(prism)[i*8])])
  prism_reduced[drug] = max_effect
}

prism_reduced

prism_reduced = prism_reduced[, !is.na(apply(prism_reduced, 2, mean, na.rm = TRUE))]

## doing the same but focusing only on ovary cell lines

prism_reduced_ovary = data.frame(row.names = rownames(df_ovary_DepMI_prism))

for (i in 1:(ncol(df_ovary_DepMI_prism)/8)){
  prism_subset_ovary = df_ovary_DepMI_prism[,(8*(i-1)+1):(8*i)]
  max_effect = apply(prism_subset_ovary, 1, min)
  drug = toString(prism.treat$name[which(rownames(prism.treat)== colnames(prism)[i*8])])
  prism_reduced_ovary[drug] = max_effect
}

prism_reduced_ovary = prism_reduced_ovary[, !is.na(apply(prism_reduced_ovary, 2, mean, na.rm = TRUE))]

prism_reduced_ovary
```


```{r c4.1 - data exploration and organization - unlist dataframe in order to compute a histogram}

## unlist dataframe to get a vector that we can work with

vector_prism_reduced_ovary <- unlist(prism_reduced_ovary)

class(vector_prism_reduced_ovary)


## computing a histogram

hist_vector_prism_reduced_ovary <- hist(vector_prism_reduced_ovary, breaks = 50, main = "Distribution of most effective treatment/proliferation values for each drug", xlab= "Proliferation values")

hist_vector_prism_reduced_ovary



# nach drugs filtern durch schwellenwert definieren
# p wert bestimmen (multiple testing problem)
```


```{r c4.2 - data exploration - defining the threshold value as zero for testing purposes in order to determine drug efficiency}

## analyzing the data a little bit further

summary(vector_prism_reduced_ovary)

quantile(vector_prism_reduced_ovary, na.rm=TRUE)

plot(vector_prism_reduced_ovary, pch=20)


## calculating values below zero

length(vector_prism_reduced_ovary)  # there are 41820 values in total

sum(vector_prism_reduced_ovary < 0, na.rm=TRUE) # 34867 show values below zero

vector_prism_reduced_ovary_negative_proliferation <- vector_prism_reduced_ovary[vector_prism_reduced_ovary < 0]

## showing summary and histogram of all values below zero

summary(vector_prism_reduced_ovary_negative_proliferation)

hist(vector_prism_reduced_ovary_negative_proliferation)
```

```{r c4.3 - data organization - determining strongest effect on proliferation on ovary cell lines by choosing the min values for each drug}

prism_reduced_ovary

## creating a vector that contains the drugs and the corresponding strongest anti-proliferating values

###for loop erstellen mit data frame
min_values_treat_prism_reduced_ovary <- apply(prism_reduced_ovary, 2, min, na.rm=TRUE)

min_values_treat_prism_reduced_ovary_vector <- as.vector(min_values_treat_prism_reduced_ovary)

## vector containing drug names and corresponding min values

names(min_values_treat_prism_reduced_ovary_vector) = colnames(prism_reduced_ovary)

## printing vector
min_values_treat_prism_reduced_ovary_vector

##trying to remove Inf values
min_values_treat_prism_reduced_ovary_vector[min_values_treat_prism_reduced_ovary_vector > 10] = 0

## displaying histogram and summary
hist(min_values_treat_prism_reduced_ovary_vector, main= "Most effective drug-proliferation values in ovary cell lines", xlab = "Minimum values for each drug")

summary(min_values_treat_prism_reduced_ovary_vector)

## setting threshold at 5% quantile
quantile(min_values_treat_prism_reduced_ovary_vector, 0.1)

hist(min_values_treat_prism_reduced_ovary_vector, main= "Most effective drug-proliferation values in ovary cell lines", xlab = "Minimum values for each drug")
abline(v=quantile(min_values_treat_prism_reduced_ovary_vector, 0.1), col="red")
```

```{r c4.4. - data organization - creating vector with ovary proliferation values that lie below threshold}

## creating vector with values smaller than threshold value at 10 % quantile

under_threshold_prism_reduced_ovary <- min_values_treat_prism_reduced_ovary_vector[min_values_treat_prism_reduced_ovary_vector < quantile(min_values_treat_prism_reduced_ovary_vector, 0.1)]

under_threshold_prism_reduced_ovary

## inspecting vector

sort(under_threshold_prism_reduced_ovary, decreasing = FALSE)
summary(under_threshold_prism_reduced_ovary)
length(under_threshold_prism_reduced_ovary)
```

```{r c4.5. - data exploration - exploring the drugs corresponding to the proliferation values below threshold}

## looking at values below threshold

hist(under_threshold_prism_reduced_ovary, xlab = "Proliferation values", main = "Under Threshold Drug-Proliferation Values in Ovary Cell Lines")

plot(under_threshold_prism_reduced_ovary, pch=20)

## creating a data frame using prism.treat that contains the relevant information in order to analyze the drugs that were used regarding the lowest proliferation values (below threshold) in ovary cell lines

reduced_prism_treat_ovary_df <- prism.treat[which(prism.treat$name %in% names(under_threshold_prism_reduced_ovary)),]


## changing the dataframe so only every 8th row is shown

reduced_prism_treat_ovary_df = reduced_prism_treat_ovary_df[seq(1, nrow(reduced_prism_treat_ovary_df),8),]

reduced_prism_treat_ovary_df

## reducing the dataframe even further and getting rid of irrelevant information

reduced_prism_treat_ovary_df_2 = reduced_prism_treat_ovary_df[,which(colnames(reduced_prism_treat_ovary_df) %in% c("broad_id", "name", "moa", "target", "disease.area", "indication"))]

reduced_prism_treat_ovary_df_2 <- droplevels(reduced_prism_treat_ovary_df_2)

reduced_prism_treat_ovary_df_2
```


```{r c4.6.1 - analyzing our data and findings}

## summary of our findings

summary(reduced_prism_treat_ovary_df_2)

vector_disease_area <- sort(as.vector(na.omit(reduced_prism_treat_ovary_df_2$disease.area)))


plot(table(reduced_prism_treat_ovary_df_2$disease.area),  las = 3)


```


```{r c4.7}

### barplot machen von kategorisierten daten
### nach dosis filtern auch noch wichtig
### hdac war am meisten dann clustern nach cell lines oder welche gene passen
### verhältnis von hdac inhibitors bei cancer cell lines im gegensatz zu allen mal schauen--> wilkixon test, (fisher, chi square -> gut für kategorisch gegen kategorisch)


##1.3 dosage response plotten -->  dosis auf x achse und effekt auf y achse
## regressionsmodell (?)

## creating a barplot with the most frequent moas

library(dplyr)
reduced_prism_treat_ovary_df_2 %>% count(moa)

testdf <- reduced_prism_treat_ovary_df_2 %>% count(moa) %>% filter(n >= 3)

testdf <- testdf[0:8,]

par(mar=c(4,20,4,4))
barplot(testdf$n, names.arg = testdf$moa, las = 1, xlab = "Frequency", horiz=TRUE)


summary(reduced_prism_treat_ovary_df_2)
```

```{r - c4.8 - analyzing HDAC inhibitors for ovary cancer cell lines}
## Extracting the data from reduced_prism_treat_ovary_df_2 where the moa is HDAC
reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "HDAC inhibitor",]

## Extracting broad IDs of HDAC moas
hdac_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "HDAC inhibitor",])$name))

## finding the matching DepMap_IDs regarding the most efficient HDAC inhibitors

ovary_cl_hdac <- vector()

for (drug in hdac_inhibitors_ovary) {
  ovary_cl_hdac <- c(ovary_cl_hdac, rownames(prism_reduced_ovary)[which(prism_reduced_ovary[drug] == min(prism_reduced_ovary[,drug], na.rm=TRUE))])
}

ovary_cl_hdac

prism.cl[prism.cl$DepMap_ID %in% ovary_cl_hdac,]
```


```{r - c4.9 - analyzing topoisomerase inhibitors for ovary cancer cell lines}


## Extracting the data from reduced_prism_treat_ovary_df_2 where the moa is topoisomerase inhibitor
reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "topoisomerase inhibitor",]

## Extracting broad IDs of topoisomerase moas
topoisomerase_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "topoisomerase inhibitor",])$name))

## finding the matching DepMap_IDs regarding the most efficient topoisomerase inhibitors

ovary_cl_topoisomerase_inhibitor <- vector()

for (drug in topoisomerase_inhibitors_ovary) {
  ovary_cl_topoisomerase_inhibitor <- c(ovary_cl_topoisomerase_inhibitor, rownames(prism_reduced_ovary)[which(prism_reduced_ovary[drug] == min(prism_reduced_ovary[,drug], na.rm=TRUE))])
}

ovary_cl_topoisomerase_inhibitor

## showing these cell lines with their prism.cl data

prism.cl[prism.cl$DepMap_ID %in% ovary_cl_topoisomerase_inhibitor,]
```



```{r - c4.10 - fisher exact test}

## fisher test topoisomerase inhibitors

fisher_topoisomerase <- data.frame(c(9,9), c(131,131), row.names = c("Ovary Cell Lines", "Non-Ovary Cell Lines"))


colnames(fisher_topoisomerase) <- c("Topoisomerase Inhibitor", "Other")

fisher_topoisomerase

fisher.test(fisher_topoisomerase)

## fisher test hdac inhibitors

fisher_hdac <- data.frame(c(10,9), c(130, 131), row.names = c("Ovary Cell Lines", "Non-Ovary Cell Lines"))


colnames(fisher_hdac) <- c("HDAC Inhibitor", "Other")

fisher_hdac

fisher.test(fisher_hdac)


## fisher test cdk inhibitor

fisher_cdk <- data.frame(c(7,5), c(133,135), row.names = c("Ovary Cell Lines", "Non-Ovary Cell Lines"))


colnames(fisher_cdk) <- c("CDK Inhibitor", "Other")

fisher_cdk

fisher.test(fisher_cdk)

## ## fisher test proteasome inhibitor

fisher_proteasome <- data.frame(c(6,4), c(134,136), row.names = c("Ovary Cell Lines", "Non-Ovary Cell Lines"))


colnames(fisher_proteasome) <- c("Proteasome Inhibitor", "Other")

fisher_proteasome

fisher.test(fisher_proteasome)

```

```{r - c4.11. clustering ovary cell lines based on their drug response}

prism_reduced_ovary_no_NAs = prism_reduced_ovary ## create a copy of prism_reduced to keep a version that includes the NAs

## creating a dataframe without NAs

for(i in 1:ncol(prism_reduced_ovary)){
  prism_reduced_ovary_no_NAs[is.na(prism_reduced_ovary[, i]), i] <- mean(prism_reduced_ovary[, i], na.rm = TRUE)
}  ## this code replaces the NAs in prism_reduced with the col mean and saves it into a new data frame called prism_reduced_ovary_no_NAs


## performing k-means and finding the optimal number of clusters by using the total within-clusters sum of squares method

km_ovary = kmeans(x=t(prism_reduced_ovary_no_NAs),
            centers = 4,
            nstart = 10)
km_ovary$cluster

str(km_ovary)

km_ovary$tot.withinss

## plotting the total within-clusters sum of squares against the number of clusers (elbow method)

wss_ovary = sapply(2:7,function(k) {
  kmeans(x=t(prism_reduced_ovary_no_NAs), centers =k)$tot.withinss
})
plot(2:7,wss_ovary,type='b',pch=19,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


## the optimal number seems to be 4 or 5 with regards to elbow method

## performing silhouette method to further analyze the optimal number of clusters

D_ovary = dist(t(prism_reduced_ovary_no_NAs))

library(cluster)

par(mfrow = c(2,3))
for (i in 3:14) {
  km_ovary = kmeans(x=t(prism_reduced_ovary_no_NAs), centers = i, nstart = 20)
  s_ovary = silhouette(km_ovary$cluster,D_ovary)
  plot(s_ovary, border=NA)
}


## clustern ohne t



km1_ovary = kmeans(prism_reduced_ovary_no_NAs,
            centers = 4,
            nstart = 10)
km1_ovary$cluster

wss1_ovary = sapply(2:15,function(k) {
  kmeans(prism_reduced_ovary_no_NAs, centers =k)$tot.withinss
})
plot(2:15,wss1_ovary,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


D1_ovary = dist(prism_reduced_ovary_no_NAs)

library(cluster)

par(mfrow = c(2,3))
for (i in 2:11) {
  km1_ovary = kmeans(prism_reduced_ovary_no_NAs, centers = i, nstart = 20)
  s1_ovary = silhouette(km1_ovary$cluster,D1_ovary)
  plot(s1_ovary, border=NA)
}

```


```{r - c4.12. visualizing the clustering of ovary cell lines based on their drug response after performing PCA}

## PCA

B = as.matrix(prism_reduced_ovary_no_NAs)

pca2 = prcomp(t(B), scale = TRUE)

plot(pca2$x[,1], pca2$x[,2], pch=20)

pca2_var = pca2$sdev^2
pca2_var_per = round(pca2_var/sum(pca2_var)*100,1)
barplot(pca2_var_per, main = "Distribution of the variation of the data explained by PCs", xlab = "Principal component", ylab = "Percent variation")

summary(prcomp(B))

## Running k-means clustering by using PC1 and PC2

wss2 = sapply(2:15,function(k) {
  kmeans(x=pca2$x[,1:2], centers = k)$tot.withinss
})
plot(2:15,wss2,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


## performing a clustering with pca data

km2 = kmeans(pca2$x[,1:2],centers=5,nstart = 100)
col = c("pink", "lightblue", "purple", "grey", "orange")
col.km2 = col[km2$cluster]
plot(pca2$x[,1], pca2$x[,2],
col= col.km2, pch=20,
xlab='PC1',ylab='PC2',
main = "PC1 vs. PC2 for kmeans clusters")

```
```{r c.4.13. - extracting the drug names of the most efficient drugs with regard to their moas}

## hdac

hdac_inhibitors_ovary

## topoisomerase

topoisomerase_inhibitors_ovary

#proteasome inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "proteasome inhibitor",]


proteasome_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "proteasome inhibitor",])$name))

proteasome_inhibitors_ovary

## PI3K inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "PI3K inhibitor",]


pi3k_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "PI3K inhibitor",])$name))

pi3k_inhibitors_ovary

## EGFR inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "EGFR inhibitor",]


egfr_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "EGFR inhibitor",])$name))

egfr_inhibitors_ovary


## CDK inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "CDK inhibitor",]


cdk_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "CDK inhibitor",])$name))

cdk_inhibitors_ovary

## BCL inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "BCL inhibitor",]


bcl_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "BCL inhibitor",])$name))

bcl_inhibitors_ovary

## ATPase inhibitor

reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "ATPase inhibitor",]

atpase_inhibitors_ovary <- as.vector(na.omit((reduced_prism_treat_ovary_df_2[reduced_prism_treat_ovary_df_2$moa == "ATPase inhibitor",])$name))

atpase_inhibitors_ovary


most_effective_ovary_moas_drugs <- c(hdac_inhibitors_ovary, topoisomerase_inhibitors_ovary, proteasome_inhibitors_ovary, pi3k_inhibitors_ovary, egfr_inhibitors_ovary, cdk_inhibitors_ovary, bcl_inhibitors_ovary, atpase_inhibitors_ovary)

most_effective_ovary_moas_drugs


## matching the drug names to their corresponding cell lines

names_use_ovary <- names(prism_reduced_ovary_no_NAs)[names(prism_reduced_ovary_no_NAs) %in% most_effective_ovary_moas_drugs]

names_use_ovary

moa_drugs_ovary <- prism_reduced_ovary_no_NAs[,names_use_ovary]

moa_drugs_ovary

```

```{r c4.14. - performing kmeans and clustering on the most efficient drugs with regard to their moas}

## performing k-means and finding the optimal number of clusters by using the total within-clusters sum of squares method

km_ovary_moa = kmeans(x=t(moa_drugs_ovary),
            centers = 4,
            nstart = 10)

km_ovary_moa$cluster

str(km_ovary_moa)

km_ovary_moa$tot.withinss

## plotting the total within-clusters sum of squares against the number of clusters (elbow method)

wss_ovary_moa = sapply(2:7,function(k) {
  kmeans(x=t(moa_drugs_ovary), centers =k)$tot.withinss
})
plot(2:7,wss_ovary_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


## the optimal number seems to be 3 or 4 with regards to the elbow method

## performing silhouette method to further analyze the optimal number of clusters

D_ovary_moa = dist(t(moa_drugs_ovary))

library(cluster)

par(mfrow = c(2,3))
for (i in 2:7) {
  km_ovary_moa = kmeans(x=t(moa_drugs_ovary), centers = i, nstart = 20)
  s_ovary_moa = silhouette(km_ovary_moa$cluster,D_ovary_moa)
  plot(s_ovary_moa, border=NA)
}


## clustern ohne t


km1_ovary_moa = kmeans(moa_drugs_ovary,
            centers = 4,
            nstart = 10)
km1_ovary_moa$cluster

wss1_ovary_moa = sapply(2:15,function(k) {
  kmeans(moa_drugs_ovary, centers =k)$tot.withinss
})
plot(2:15,wss1_ovary_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


D1_ovary_moa = dist(moa_drugs_ovary)

library(cluster)

par(mfrow = c(2,3))
for (i in 2:11) {
  km1_ovary_moa = kmeans(moa_drugs_ovary, centers = i, nstart = 20)
  s1_ovary_moa = silhouette(km1_ovary_moa$cluster,D1_ovary_moa)
  plot(s1_ovary_moa, border=NA)
}

```




```{r c.4.15 - visualizing the clusters; clustering by drugs}

B_moa = as.matrix(moa_drugs_ovary)

pca2_moa_t = prcomp(t(B_moa), scale = TRUE)

plot(pca2_moa_t$x[,1], pca2_moa_t$x[,2], pch=20)

pca2_var_moa_t = pca2_moa_t$sdev^2
pca2_var_per_moa_t = round(pca2_var_moa_t/sum(pca2_var_moa_t)*100,1)
barplot(pca2_var_per_moa_t, main = "Distribution of the variation of the data explained by PCs", xlab = "Principal component", ylab = "Percent variation")

summary(prcomp(B_moa))

## Running k-means clustering by using PC1 and PC2

wss2_moa_t = sapply(2:7,function(k) {
  kmeans(x=pca2_moa_t$x[,1:2], centers = k)$tot.withinss
})
plot(2:7,wss2_moa_t,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


## performing a clustering with pca data

km2_moa_t = kmeans(pca2_moa_t$x[,1:2],centers=4,nstart = 100)
col = c("red", "orange", "blue", "green")
col.km2_moa_t = col[km2_moa_t$cluster]
plot(pca2_moa_t$x[,1], pca2_moa_t$x[,2],
col= col.km2_moa_t, pch=20,
xlab='PC1',ylab='PC2',
main = "PC1 vs. PC2 for kmeans clusters - clustering by drugs")
legend("topright", legend = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4"), fill = col)

```





```{r c.4.16 - visualizing the clusters; clustering by cell lines }

B_moa = as.matrix(moa_drugs_ovary)

pca2_moa = prcomp(B_moa, scale = TRUE)

plot(pca2_moa$x[,1], pca2_moa$x[,2], pch=20)

pca2_var_moa = pca2_moa$sdev^2
pca2_var_per_moa = round(pca2_var_moa/sum(pca2_var_moa)*100,1)
barplot(pca2_var_per_moa, main = "Distribution of the variation of the data explained by PCs", xlab = "Principal component", ylab = "Percent variation")

summary(prcomp(B_moa))

## Running k-means clustering by using PC1 and PC2

wss2_moa = sapply(2:7,function(k) {
  kmeans(x=pca2_moa$x[,1:2], centers = k)$tot.withinss
})
plot(2:7,wss2_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


## performing a clustering with pca data

km2_moa = kmeans(pca2_moa$x[,1:2],centers=4,nstart = 100)
col = c("red", "orange", "blue", "green")
col.km2_moa = col[km2_moa$cluster]
plot(pca2_moa$x[,1], pca2_moa$x[,2],
col= col.km2_moa, pch=20,
xlab='PC1',ylab='PC2',
main = "PC1 vs. PC2 for kmeans clusters - clustering by cell lines")
legend("topright", legend = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4"), fill = col)


barplot(sort(pca2_moa$rotation[,1]), las=3, cex.names = 0.4)


barplot(sort(pca2_moa$rotation[,2]), las=3, cex.names = 0.4)
```




```{r S1 Creating a dataframe including only the lowest proliferations values of each drug treatment}

## Reducing prism to include only the lowest proliferation value of each drug treatment on all cell lines

prism_reduced = data.frame(row.names = rownames(prism))

for (i in 1:(ncol(prism)/8)){
  prism_subset = prism[,(8*(i-1)+1):(8*i)]
  max_effect = apply(prism_subset, 1, min)
  drug = toString(prism.treat$name[which(rownames(prism.treat)== colnames(prism)[i*8])])
  prism_reduced[drug] = max_effect
}

## Extracting the lowest proliferation values of each drug for all cell lines except the ovary cell lines
prism_reduced = prism_reduced[-which(rownames(prism_reduced) %in% vector_ovary_DepMI),]

prism_reduced = prism_reduced[, !is.na(apply(prism_reduced, 2, mean, na.rm = TRUE))]
```

```{r S2 Plotting the data from prism_reduced}

## Plotting a histogramm of prism_reduced visualizing the lowest proliferation values for all cell lines except ovary
hist_prism_reduced <- hist(unlist(prism_reduced), xlab = "Proliferation values", main = "Proliferation values of prism_reduced for every drug", breaks = 100)

```

```{r S3 Replacing NAs in prism_reduced with the column means}

## Creating a copy of prism_reduced to keep a version that includes the NAs
prism_reduced_no_NAs = prism_reduced

## Replacing the NAs in prism_reduced with the col mean and saving it into a new data frame called prism_reduced_no_NAs

for(i in 1:ncol(prism_reduced)){
  prism_reduced_no_NAs[is.na(prism_reduced[, i]), i] <- mean(prism_reduced[, i], na.rm = TRUE)
}  

## Plotting a histogram of the lowest proliferation values without NAs for all cell lines except ovary
hist(unlist(prism_reduced_no_NAs), breaks = 100, xlab = "Proliferation values", main = "Proliferation values of prism_reduced_no_NAs for every drug")
```

```{r S4 Defining a threshhold in order to remove insignificant drugs from prism_reduced}

## Creating a vector that contains the drugs and the corresponding strongest anti-proliferating values
min_values_treat_prism_reduced <- apply(prism_reduced, 2, min, na.rm=TRUE)

min_values_treat_prism_reduced_vector <- as.vector(min_values_treat_prism_reduced)

## Vector containing drug names and corresponding min values
names(min_values_treat_prism_reduced_vector) = colnames(prism_reduced)

## Removing Inf values
min_values_treat_prism_reduced_vector[min_values_treat_prism_reduced_vector > 10] = 0

## Setting threshold at 5% quantile
quantile(min_values_treat_prism_reduced_vector, 0.1)

## Plotting a histogram of the most effective proliferation values in all cell lines except ovary with a red line marking the 5% threshhold
hist(min_values_treat_prism_reduced_vector, main = "Most effective proliferation values in all cell lines except ovary", xlab = "Proliferation values")
abline(v=quantile(min_values_treat_prism_reduced_vector, 0.1), col="red")

min_values_treat_prism_reduced_vector_no_Inf = min_values_treat_prism_reduced_vector

## Creating a vector with all of the min values in prism_reduced under the threshold of the 5% quantile
prism_reduced_under_threshold = data.frame(min_values_treat_prism_reduced[min_values_treat_prism_reduced < quantile(min_values_treat_prism_reduced_vector, 0.1)])

```


```{r S6 Finding the cell lines corresponding to the lowest proliferation value of each drug}

## Reducing prism.treat so that it only includes the data for the proliferation values under the threshold
prism.treat_reduced <- prism.treat[which(prism.treat$name %in% rownames(prism_reduced_under_threshold)),]

```

```{r S7 Finding out if the medications in the 5% quantile are oncological/non-oncological}

## Selecting every 8th row of prism.treat_reduced
prism.treat_reduced = prism.treat_reduced[seq(1, nrow(prism.treat_reduced),8),]

prism.treat_reduced = droplevels(prism.treat_reduced)

## Creating a new dataframe that only includes columns that are interesting for us
prism.treat_reduced_2 = prism.treat_reduced[,which(colnames(prism.treat_reduced) %in% c("name", "moa", "target", "disease.area", "indication", "broad_id"))]

```

```{r S8 Analysing our data}

## Plotting the number of medications belonging to the disease areas included in prism.treat_reduced
plot(table(prism.treat_reduced$disease.area), srt = 90, las = 3, ylab = "Frequency", main = "Frequency of selected medications in prism.treat_reduced")

## Sorting the moa values in prism.treat_reduced alphabetically
sort(unique(as.vector(na.omit(prism.treat_reduced$moa))))

## Creating a barplot with the moas of the prims.treat_reduced_2 dataframe
barplot(which(as.list(prism.treat_reduced_2$moa)>1)) ## not nexessary??

##Creating dataframe which includes the frequency of the different moas in prism.treat_reduced_2
library(dplyr)

prism.treat_reduced_2 %>% count(moa)

moa_frequencies = prism.treat_reduced_2 %>% count(moa) %>% filter(n >= 3)

moa_frequencies = moa_frequencies[0:9,]


prism.treat_reduced_2 %>% count(moa) %>% filter(n >= 3) %>% .$x

as.vector((prism.treat_reduced_2 %>% count(moa) %>% filter(n >= 3) %>% .$x)$n)

##Plotting the frequency of the different moas
par(mar=c(4, 20, 4, 4))
barplot(moa_frequencies$n, names.arg = moa_frequencies$moa, las = 1, xlab = "Frequency", horiz = TRUE, xlim = c(0,10), main = "Most frequent moa's amongst the medications under the threshhold")

```

```{r S9 Finding the cell lines, in which HDAC was the mechanism of action}

## Extracting the data from prism.treat_reduced_2 where the moa is HDAC
prism.treat_reduced_2[prism.treat_reduced_2$moa == "HDAC inhibitor",]

## Extracting the medication names of HDAC moas
hdac_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "HDAC inhibitor",])$name))

## Extracting the DepmapIDs that the above found out medications were used on
cl_hdac = vector()
for (drug in hdac_inhibitors) {
  cl_hdac = c(cl_hdac, rownames(prism_reduced)[which(prism_reduced[drug] == min(prism_reduced[,drug], na.rm = TRUE))])
}

## Finding the matching cell lines
prism.cl[prism.cl$DepMap_ID %in% cl_hdac,]

```

```{r S 10 Finding the cell lines, in which the topoisomerase inhibitor was the mechanism of action}

## Extracting the data from prism.treat_reduced_2 where the moa is topoisomerase inhibitor
prism.treat_reduced_2[prism.treat_reduced_2$moa == "topoisomerase inhibitor",]

## Extracting the medication names of topoisomerase moas
topoisomerase_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "topoisomerase inhibitor",])$name))

## Extracting the DepmapIDs that the above found out medications were used on
cl_topoisomerase_inhibitor = vector()
for (drug in topoisomerase_inhibitors) {
  cl_topoisomerase_inhibitor = c(cl_topoisomerase_inhibitor, rownames(prism_reduced)[which(prism_reduced[drug] == min(prism_reduced[,drug], na.rm = TRUE))])
}

## Finding the matching cell lines
prism.cl[prism.cl$DepMap_ID %in% cl_topoisomerase_inhibitor,]

```

```{r S11 Finding the names of the medications used in the cell lines in which the following moas were active: topoisomerase inhibitor, proteasome inhibitor, PI3K inhibitor, NFkB pathway inhibitor, HDAC, EGFR, CDK, BCL, and ATPase}

## Extracting the medication names of topoisomerase moas
topoisomerase_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "topoisomerase inhibitor",])$name))

## Extracting the medication names of proteasome moas
proteasome_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "proteasome inhibitor",])$name))

## Extracting the medication names of PI3K moas
PI3K_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "PI3K inhibitor",])$name))

## Extracting the medication names of NFkB_pathway moas
NFkB_pathway_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "NFkB_pathway inhibitor",])$name))

## Extracting the medication names of HDAC moas
hdac_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "HDAC inhibitor",])$name))

## Extracting the medication names of EGFR moas
EGFR_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "EGFR inhibitor",])$name))

## Extracting the medication names of CDK moas
CDK_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "CDK inhibitor",])$name))

## Extracting the medication names of BCL moas
BCL_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "BCL inhibitor",])$name))

## Extracting the medication names of ATPase moas
ATPase_inhibitors = as.vector(na.omit((prism.treat_reduced_2[prism.treat_reduced_2$moa == "ATPase inhibitor",])$name))

## Combining all the medication names into one vector

most_effective_moas_drugs = c(topoisomerase_inhibitors, proteasome_inhibitors, PI3K_inhibitors, NFkB_pathway_inhibitors, hdac_inhibitors, EGFR_inhibitors, CDK_inhibitors, BCL_inhibitors, ATPase_inhibitors)

## Extracting the cell lines that these selected drugs worked best on and adding the proliferation values

names_use <- names(prism_reduced_no_NAs)[names(prism_reduced_no_NAs) %in% most_effective_moas_drugs]

moa_drugs <- prism_reduced_no_NAs[,names_use]

```


```{r S12 Clustering moa_drugs by cell lines}

## Elbow plot
wss1_all_moa = sapply(2:15,function(k) {
  kmeans(moa_drugs, centers =k)$tot.withinss
})
plot(2:15,wss1_all_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

## Silhouette plot
D1_all_moa = dist(moa_drugs)

## kmeans clustering
library(cluster)
km1_all_moa = kmeans(moa_drugs, centers = 4, nstart = 10)
s1_all_moa= silhouette(km1_all_moa$cluster, D1_all_moa, col="red")
plot(s1_all_moa, border = NA)

## For loop checking how many centers are best
par(mfrow = c(2,3))
for (i in 3:14){
  km1_all_moa = kmeans(moa_drugs, centers = i, nstart = 20)
  s1_all_moa= silhouette(km1_all_moa$cluster, D1_all_moa, col="red")
  plot(s1_all_moa, border = NA)
}

```

```{r S13 Clustering moa_drugs by medications}

## Elbow plot
wss_all_moa = sapply(2:7,function(k) {
  kmeans(x=t(moa_drugs), centers =k)$tot.withinss
})
plot(2:7,wss_all_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

## Silhouette plot
D_all_moa = dist(x=t(moa_drugs))

library(cluster)
km_all_moa = kmeans(x=t(moa_drugs), centers = 4, nstart = 10)
s_all_moa = silhouette(km_all_moa$cluster, D_all_moa, col="red")
plot(s_all_moa, border = NA)

## For loop checking how many centers are best
par(mfrow = c(2,3))
for (i in 3:14){
  km_all_moa = kmeans(x=t(moa_drugs), centers = i, nstart = 20)
  s_all_moa = silhouette(km_all_moa$cluster, D_all_moa, col="red")
  plot(s_all_moa, border = NA)
}


```

```{r S14 PCA by cell lines}

A_moa = as.matrix(moa_drugs)

pca1_moa = prcomp(A_moa, scale = TRUE)

plot(pca1_moa$x[,1], pca1_moa$x[,2], pch=20)

pca1_var_moa = pca1_moa$sdev^2
pca1_var_per_moa = round(pca1_var_moa/sum(pca1_var_moa)*100,1)
barplot(pca1_var_per_moa, main = "Distribution of the variation of the data explained by PCs", xlab = "Principal component", ylab = "Percent variation")

summary(prcomp(A_moa))


wss_all_moa = sapply(2:15,function(k) {
  kmeans(x=pca1_moa$x[,1:2], centers =k)$tot.withinss
})
plot(2:15,wss_all_moa,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

km1_moa = kmeans(pca1_moa$x[,1:2],centers=5,nstart = 100)
col = c('green','blue','red', "orange", "brown")
col.km1_moa = col[km1_moa$cluster]
plot(pca1_moa$x[,1], pca1_moa$x[,2],
col= col.km1_moa, pch=20,
xlab='PC1',ylab='PC2',
main = "PC1 vs. PC2 for kmeans clusters
Clustering moa_drugs by cell lines")
legend("topleft", legend = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5"), fill = col)

barplot(sort(pca1_moa$rotation[,1]), las=3, cex.names=0.4)

barplot(sort(pca1_moa$rotation[,2]), las=3, cex.names=0.4)

```

```{r S15 PCA by medications}

A_moa = as.matrix(moa_drugs)

pca1_moa_t = prcomp(t(A_moa), scale = TRUE)

plot(pca1_moa_t$x[,1], pca1_moa_t$x[,2], pch=20)

pca1_var_moa_t = pca1_moa_t$sdev^2
pca1_var_per_moa_t = round(pca1_var_moa_t/sum(pca1_var_moa_t)*100,1)
barplot(pca1_var_per_moa_t, main = "Distribution of the variation of the data explained by PCs", xlab = "Principal component", ylab = "Percent variation")

summary(prcomp(A_moa))


wss_all_moa_t = sapply(2:15,function(k) {
  kmeans(x=pca1_moa_t$x[,1:2], centers =k)$tot.withinss
})
plot(2:15,wss_all_moa_t,type='b',pch=20,xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")


km_moa = kmeans(pca1_moa_t$x[,1:2],centers=4,nstart = 100)
col = c('green','blue','red', "orange", "brown", "pink", "black", "gray")
col.km_moa = col[km_moa$cluster]
plot(pca1_moa_t$x[,1], pca1_moa_t$x[,2],
col= col.km_moa, pch=20,
xlab='PC1',ylab='PC2',
main = "PC1 vs. PC2 for kmeans clusters
Clustering moa_drugs by medications")
legend("topleft", legend = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4"), fill = col)

```

```{r}


```
