---
title: "Milestone 2.2 Versuch 1"
author: "Laura Diekmann"
date: "8 7 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("/Users/laura/OneDrive/Dokumente/Environment2.2.RData")
library(dplyr)
library(tidyr)
library(tibble)
```

```{r}

## cluster out of Milestone 1.1 1.2 the most effective ovarycelllines
km2_moa$cluster

# Extract celllines from prism.achilles which belong to cluster 1

achilles_vector_cluster1 = as.vector(na.omit(names(which(km2_moa$cluster == 1))))
achilles_vector_cluster1

# Extract celllines from prism.achilles which belong to cluster 2
achilles_vector_cluster2 = as.vector(na.omit(names(which(km2_moa$cluster == 2))))
achilles_vector_cluster2

# Extract celllines from prism.achilles which belong to cluster 3
achilles_vector_cluster3 = as.vector(na.omit(names(which(km2_moa$cluster == 3))))
achilles_vector_cluster3


# Extract celllines from prism.achilles which belong to cluster 4
achilles_vector_cluster4 = as.vector(na.omit(names(which(km2_moa$cluster == 4))))
achilles_vector_cluster4

# Reduce prism.achilles dataset to the selected celllines from the clusters
ovary_achilles_cluster1 <- prism.achilles[rownames(prism.achilles) %in% achilles_vector_cluster1,]
ovary_achilles_cluster1

ovary_achilles_cluster2 <- prism.achilles[rownames(prism.achilles) %in% achilles_vector_cluster2,]
ovary_achilles_cluster2

ovary_achilles_cluster3 <- prism.achilles[rownames(prism.achilles) %in% achilles_vector_cluster3,]
ovary_achilles_cluster3

ovary_achilles_cluster4 <- prism.achilles[rownames(prism.achilles) %in% achilles_vector_cluster4,]
ovary_achilles_cluster4
```
```{r}
df_ovary_prism_treat_effective_long
## only the celllines out of cluster 1,2,3,4 in dataframe df_ovary_prism_treat_effective_long to select the drugs that work the best

##cluster 1
df_ovary_prism_treat_effective_long_c1<- df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$DepMap_ID %in%achilles_vector_cluster1 ,]
df_ovary_prism_treat_effective_long_c1

##cluster 2
df_ovary_prism_treat_effective_long_c2<- df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$DepMap_ID %in%achilles_vector_cluster2,]
df_ovary_prism_treat_effective_long_c2

##cluster 3
df_ovary_prism_treat_effective_long_c3<- df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$DepMap_ID %in%achilles_vector_cluster3,]
df_ovary_prism_treat_effective_long_c3

##cluster 4
df_ovary_prism_treat_effective_long_c4<- df_ovary_prism_treat_effective_long[df_ovary_prism_treat_effective_long$DepMap_ID %in%achilles_vector_cluster4,]
df_ovary_prism_treat_effective_long_c4

```

```{r}
## only the ovary celllines out of cluster 1,2,3,4 in dataframe  to select the drugs that work the best
prism_reduced_noovary = prism[-which(rownames(prism)%in% vector_ovary_DepMI),]
prism_reduced_noovary

##as.vector names of only cellines without ovary

vector_all_DepMI<-as.vector(rownames(prism_reduced_noovary))

##flipping x and y achsis
new_prism_reduced_noovary<- as.data.frame(t(prism_reduced_noovary))
new_prism_reduced_noovary

##creating a dataframe from the ovary cell lines with DepMApID,ploriferation values, broad ID und dose
df_noovary_DepMI_prism_treat <-merge(prism.treat,new_prism_reduced_noovary, by="row.names")
df_noovary_DepMI_prism_treat

##deleting all other columns 
df_noovary_DepMI_prism_treat[,c('screen_id','compound_plate','moa','target','disease.area','indication','smiles','phase')]<-list(NULL)

df_noovary_DepMI_prism_treat

## the most effective drugs in a vector
most_effective_moas_drugs2<-c("TAS-103","nemorubicin","idarubicin","10-hydroxycamptothecin", "amsacrine","SN-38","doxorubicin","exatecan-mesylate","genz-644282","ixazomib-citrate","carfilzomib","delanzomib","ixazomib","BGT226","buparlisib","CUDC-907","PCI-24781","AR-42", "givinostat","scriptaid","M-344","romidepsin","trichostatin-a","vorinostat","JNJ-26481585","pelitinib","PD-168393","dacomitinib","afatinib","AT-7519","dinaciclib","CR8-(R)","P276-00" ,"R547","oridonin","obatoclax","HA14-1","TW-37","digoxin","thonzonium","digitoxigenin","NMS-873")

##reducing to only the effective moa drugs out of Milestone 1.1 , 1.2 
df_noovary_prism_treat_effective <- df_noovary_DepMI_prism_treat[df_noovary_DepMI_prism_treat$name %in% most_effective_moas_drugs2,]
df_noovary_prism_treat_effective 

```

```{r}
##making a long dataframe

df_noovary_prism_treat_effective_long<-pivot_longer(df_noovary_prism_treat_effective,cols = starts_with("ACH"),names_to= "DepMap_ID", values_to="proliferationvalues", values_drop_na=TRUE)
df_noovary_prism_treat_effective_long
```
```{r}
## cluster out of Milestone 1.1 1.2 the most effective ovarycelllines
km1_moa$cluster

# Extract celllines from prism.achilles which belong to cluster 1

achilles_noovary_vector_cluster1 = as.vector(na.omit(names(which(km1_moa$cluster == 1))))
achilles_noovary_vector_cluster1

# Extract celllines from prism.achilles which belong to cluster 2
achilles_noovary_vector_cluster2 = as.vector(na.omit(names(which(km1_moa$cluster == 2))))
achilles_noovary_vector_cluster2

# Extract celllines from prism.achilles which belong to cluster 3
achilles_noovary_vector_cluster3 = as.vector(na.omit(names(which(km1_moa$cluster == 3))))
achilles_noovary_vector_cluster3


# Extract celllines from prism.achilles which belong to cluster 4
achilles_noovary_vector_cluster4 = as.vector(na.omit(names(which(km1_moa$cluster == 4))))
achilles_noovary_vector_cluster4


achilles_noovary_vector_cluster5 = as.vector(na.omit(names(which(km1_moa$cluster == 5))))
achilles_noovary_vector_cluster5

# Reduce prism.achilles dataset to the selected celllines from the clusters
noovary_achilles_cluster1 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster1,]
noovary_achilles_cluster1

noovary_achilles_cluster2 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster2,]
noovary_achilles_cluster2

noovary_achilles_cluster3 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster3,]
noovary_achilles_cluster3

noovary_achilles_cluster4 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster4,]
noovary_achilles_cluster4

noovary_achilles_cluster5 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster5,]
noovary_achilles_cluster5
```


```{r}
## only the celllines out of cluster 1,2,3,4 in dataframe df_ovary_prism_treat_effective_long to select the drugs that work the best

##cluster 1
df_noovary_prism_treat_effective_long_c1<- df_noovary_prism_treat_effective_long[df_noovary_prism_treat_effective_long$DepMap_ID %in%achilles_noovary_vector_cluster1 ,]
df_noovary_prism_treat_effective_long_c1

##cluster 2
df_noovary_prism_treat_effective_long_c2<- df_noovary_prism_treat_effective_long[df_noovary_prism_treat_effective_long$DepMap_ID %in%achilles_noovary_vector_cluster2,]
df_noovary_prism_treat_effective_long_c2

##cluster 3
df_noovary_prism_treat_effective_long_c3<- df_noovary_prism_treat_effective_long[df_noovary_prism_treat_effective_long$DepMap_ID %in%achilles_noovary_vector_cluster3,]
df_noovary_prism_treat_effective_long_c3

##cluster 4
df_noovary_prism_treat_effective_long_c4<- df_noovary_prism_treat_effective_long[df_noovary_prism_treat_effective_long$DepMap_ID %in%achilles_noovary_vector_cluster4,]
df_noovary_prism_treat_effective_long_c4

##cluster 5
df_noovary_prism_treat_effective_long_c5<- df_noovary_prism_treat_effective_long[df_noovary_prism_treat_effective_long$DepMap_ID %in%achilles_noovary_vector_cluster5,]
df_noovary_prism_treat_effective_long_c5
```
```{r}
##for interest correlation matrix for nonovary cell lines
cordf_effective_noovary= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  cordf_effective_noovary[drug]=apply(response,1,function(x){cor(x,dose)})
}
cordf_effective_noovary<-cordf_effective_noovary[rownames(cordf_effective_noovary) %in% vector_all_DepMI,]
cordf_effective_noovary
```

```{r}
##vizualising the correlation from the non ovary cell lines

cormatrix_effective_noovary<- data.matrix(cordf_effective_noovary)
cormatrix_effective_noovary
dim(cormatrix_effective_noovary)
library(ggcorrplot)
##visualization the correlation using ggplot2
ggplot2_dose_proliferation_noovary<-ggcorrplot(cormatrix_effective_noovary)
ggplot2_dose_proliferation_noovary

hist(cormatrix_effective_noovary, xlab="Pearson Correlationvalues",main= paste("Pearson Correlation Histogram"))
```

```{r}
## doing a boxplot with noovary cellines to compare to ovary celllines
ggplot_dose_proliferationvalues_noovary<-ggplot(df_noovary_prism_treat_effective_long, aes(x=dose, y=proliferationvalues)) +
  geom_point()+
  labs(title="Plot of proliferation value per dose",x="Dose (µm)", y = "proliferation value")
ggplot_dose_proliferationvalues_noovary

df_noovary_prism_treat_effective_long$dose_high_low <- df_noovary_prism_treat_effective_long$dose
for(i in 1:nrow(df_noovary_prism_treat_effective_long)){
  if(df_noovary_prism_treat_effective_long$dose[i] < 2){
    df_noovary_prism_treat_effective_long$dose_high_low[i]="0<=2"
  } else if(df_noovary_prism_treat_effective_long$dose[i] >= 2 & df_noovary_prism_treat_effective_long$dose[i] <= 7.5){
    df_noovary_prism_treat_effective_long$dose_high_low[i]="2<7.5"
  } else if(df_noovary_prism_treat_effective_long$dose[i] > 7.5){
    df_noovary_prism_treat_effective_long$dose_high_low[i]="7.5<11"
  }
}

df_noovary_prism_treat_effective_long

#ggplot_dose_proliferationvalues2<-ggplot(df_ovary_prism_treat_effective_long, aes(x=dose_high_low, y=proliferationvalues, group= DepMap_ID)) +
#  geom_boxplot()



ggplot_plot_boxplot_dose_proliferation_noovary <- ggplot(df_noovary_prism_treat_effective_long, aes(x=dose_high_low, y=proliferationvalues)) + geom_boxplot(outlier.shape=8, aes(fill=dose_high_low))+labs(title="Plot of proliferation value per dose",x="Dose (µm)", y = "Proliferation value")
ggplot_plot_boxplot_dose_proliferation_noovary

```

```{r}
##for c1 cluster ovary
##comparing the mean values of both non ovary and ovary celllines
##creating a dataframe with mean values of proliferationrates orderd after ovary celllines  
mean_effective_ovary1= data.frame(row.names=rownames(prism))

for (drug in unique(df_ovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary1[drug]=apply(response,1,function(x){mean(x,na.rm=TRUE)})
}
mean_effective_ovary1<-mean_effective_ovary1[rownames(mean_effective_ovary1) %in% achilles_vector_cluster1,]
mean_effective_ovary1



##minimal mean value
mean_effective_ovary_mean1<-data.frame(apply(mean_effective_ovary1,2,mean, na.rm=TRUE))
mean_effective_ovary_mean1

##where is the minimal value
which(mean_effective_ovary_mean1==min(mean_effective_ovary_mean1), arr.ind =TRUE)

##for cluster 1 non ovary
##creating a dataframe with mean values of proliferationrates orderd after non ovary celllines
mean_effective_noovary1= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary1[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary1<-mean_effective_noovary1[rownames(mean_effective_noovary1) %in% achilles_noovary_vector_cluster1,]
mean_effective_noovary1


##minimal mean value
mean_effective_noovary_mean1<-data.frame(apply(mean_effective_noovary1,2,mean, na.rm=TRUE))
mean_effective_noovary_mean1
##where is the minimal value
which(mean_effective_noovary_mean1==min(mean_effective_noovary_mean1), arr.ind =TRUE)
```




```{r}
##cluster 2 ovary
mean_effective_ovary2= data.frame(row.names=rownames(prism))

for (drug in unique(df_ovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary2[drug]=apply(response,1,function(x){mean(x,na.rm=TRUE)})
}
mean_effective_ovary2<-mean_effective_ovary2[rownames(mean_effective_ovary2) %in% achilles_vector_cluster2,]
mean_effective_ovary2



##minimal mean value
mean_effective_ovary_mean2<-data.frame(apply(mean_effective_ovary2,2,mean, na.rm=TRUE))
mean_effective_ovary_mean2

##where is the minimal value
which(mean_effective_ovary_mean2==min(mean_effective_ovary_mean2), arr.ind =TRUE)

##non ovary cluster 2
##creating a dataframe with mean values of proliferationrates orderd after non ovary celllines
mean_effective_noovary2= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary2[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary2<-mean_effective_noovary2[rownames(mean_effective_noovary2) %in% achilles_noovary_vector_cluster2,]
mean_effective_noovary2


##minimal mean value
mean_effective_noovary_mean2<-data.frame(apply(mean_effective_noovary2,2,mean, na.rm=TRUE))
mean_effective_noovary_mean2
##where is the minimal value
which(mean_effective_noovary_mean2==min(mean_effective_noovary_mean2), arr.ind =TRUE)
```




```{r}
##cluster 3 ovary
mean_effective_ovary3= data.frame(row.names=rownames(prism))

for (drug in unique(df_ovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary3[drug]=apply(response,1,function(x){mean(x,na.rm=TRUE)})
}
mean_effective_ovary3<-mean_effective_ovary3[rownames(mean_effective_ovary3) %in% achilles_vector_cluster3,]
mean_effective_ovary3



##minimal mean value
mean_effective_ovary_mean3<-data.frame(apply(mean_effective_ovary3,2,mean, na.rm=TRUE))
mean_effective_ovary_mean3

##where is the minimal value
which(mean_effective_ovary_mean3==min(mean_effective_ovary_mean3), arr.ind =TRUE)

##non ovary cluster 3
##creating a dataframe with mean values of proliferationrates orderd after non ovary celllines
mean_effective_noovary3= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary3[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary3<-mean_effective_noovary3[rownames(mean_effective_noovary3) %in% achilles_noovary_vector_cluster3,]
mean_effective_noovary3


##minimal mean value
mean_effective_noovary_mean3<-data.frame(apply(mean_effective_noovary3,2,mean, na.rm=TRUE))
mean_effective_noovary_mean3
##where is the minimal value
which(mean_effective_noovary_mean3==min(mean_effective_noovary_mean3), arr.ind =TRUE)
```
```{r}
##cluster 4 ovary
mean_effective_ovary4= data.frame(row.names=rownames(prism))

for (drug in unique(df_ovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary4[drug]=apply(response,1,function(x){mean(x,na.rm=TRUE)})
}
mean_effective_ovary4<-mean_effective_ovary4[rownames(mean_effective_ovary4) %in% achilles_vector_cluster4,]
mean_effective_ovary4



##minimal mean value
mean_effective_ovary_mean4<-data.frame(apply(mean_effective_ovary4,2,mean, na.rm=TRUE))
mean_effective_ovary_mean4

##where is the minimal value
which(mean_effective_ovary_mean4==min(mean_effective_ovary_mean4), arr.ind =TRUE)

##non ovary cluster 4
##creating a dataframe with mean values of proliferationrates orderd after non ovary celllines
mean_effective_noovary4= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary4[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary4<-mean_effective_noovary4[rownames(mean_effective_noovary4) %in% achilles_noovary_vector_cluster4,]
mean_effective_noovary4


##minimal mean value
mean_effective_noovary_mean4<-data.frame(apply(mean_effective_noovary4,2,mean, na.rm=TRUE))
mean_effective_noovary_mean4
##where is the minimal value
which(mean_effective_noovary_mean4==min(mean_effective_noovary_mean4), arr.ind =TRUE)
```
```{r}

##non ovary cluster 5
##creating a dataframe with mean values of proliferationrates orderd after non ovary celllines
mean_effective_noovary5= data.frame(row.names=rownames(prism))

for (drug in unique(df_noovary_prism_treat_effective_long$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary5[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary5<-mean_effective_noovary5[rownames(mean_effective_noovary5) %in% achilles_noovary_vector_cluster5,]
mean_effective_noovary5


##minimal mean value
mean_effective_noovary_mean5<-data.frame(apply(mean_effective_noovary5,2,mean, na.rm=TRUE))
mean_effective_noovary_mean5
##where is the minimal value
which(mean_effective_noovary_mean5==min(mean_effective_noovary_mean5), arr.ind =TRUE)
```

```{r}
## looking at one drug which is responding to those cluster differently between 3 and 4
##mean for 4
mean_effective_ovary_new4= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary_new4[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovary_new4<-mean_effective_ovary_new4[rownames(mean_effective_ovary_new4) %in% achilles_vector_cluster4,]
mean_effective_ovary_new4

##mean for 3
mean_effective_ovarynew3= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovarynew3[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovarynew3<-mean_effective_ovarynew3[rownames(mean_effective_ovarynew3) %in% achilles_vector_cluster3,]
mean_effective_ovarynew3

##for each column dfovary and dfnonovary t-test
pvalues_t_test_treat3vs4<-data.frame(mapply(function(x,y)t.test(x,y,na.rm=TRUE,alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,mean_effective_ovary_new4,mean_effective_ovarynew3))
pvalues_t_test_treat3vs4

##creatig a dataframe with p-vaues and genes
pvalues_t_test_treat3vs4<-rename(pvalues_t_test_treat3vs4,p_value=mapply.function.x..y..t.test.x..y..na.rm...TRUE..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_treat3vs4$Bonferroni <-
      p.adjust(pvalues_t_test_treat3vs4$p_value,
               method = "bonferroni")


pvalues_t_test_treat3vs4

##ranking the drugs
dplyr::arrange(pvalues_t_test_treat3vs4, Bonferroni)
```
```{r}
##important
## looking at one drug which is responding to those cluster differently between 1 and 3
##mean for cluster 1
mean_effective_ovary_new1= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary_new1[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovary_new1<-mean_effective_ovary_new1[rownames(mean_effective_ovary_new1) %in% achilles_vector_cluster1,]
mean_effective_ovary_new1

##mean for cluster 3
mean_effective_ovarynew3= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovarynew3[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovarynew3<-mean_effective_ovarynew3[rownames(mean_effective_ovarynew3) %in% achilles_vector_cluster3,]
mean_effective_ovarynew3

##for each column 1vs3 t-test
pvalues_t_test_treat3vs1<-data.frame(mapply(function(x,y)t.test(x,y,na.rm=TRUE,alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,mean_effective_ovary_new1,mean_effective_ovarynew3))
pvalues_t_test_treat3vs1

##creatig a dataframe with p-vaues and genes
pvalues_t_test_treat3vs1<-rename(pvalues_t_test_treat3vs1,p_value=mapply.function.x..y..t.test.x..y..na.rm...TRUE..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_treat3vs1$Bonferroni <-
      p.adjust(pvalues_t_test_treat3vs1$p_value,
               method = "bonferroni")


pvalues_t_test_treat3vs1

##ranking the drugs
pvalues_t_test_treat3vs1<-dplyr::arrange(pvalues_t_test_treat3vs1, Bonferroni)
pvalues_t_test_treat3vs1
```
```{r}
##extra dataframe for the report to show the solutions from the t.test at prism.treat
pvalues_t_test_treat3vs1_reduced<-pvalues_t_test_treat3vs1[rownames(pvalues_t_test_treat3vs1)%in% c("trichostatin-a","semaxanib","alvocidib"),]
pvalues_t_test_treat3vs1_reduced
```

```{r}
## only those 3 drugs in one dataframe
##looking into SN38
selected_drug_ovary1<-select(mean_effective_ovary_new1, c("trichostatin-a","semaxanib","alvocidib"))
selected_drug_ovary1
selected_drug_ovary3<-select(mean_effective_ovarynew3,c("trichostatin-a","semaxanib","alvocidib"))
selected_drug_ovary3
```

```{r}
## looking at the genes from cluster 1 and 3 and doing a t-test

##for each column df1 and df3 welch t-test (assuming anequal variance)
pvalues_t_test_achilles_new1vs3<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,ovary_achilles_cluster1,ovary_achilles_cluster3))

pvalues_t_test_achilles_new1vs3

##creatig a dataframe with p-values and genes
pvalues_t_test_achilles_new1vs3<-dplyr::rename(pvalues_t_test_achilles_new1vs3,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_achilles_new1vs3$Bonferroni <-
      p.adjust(pvalues_t_test_achilles_new1vs3$p_value,
               method = "bonferroni")

pvalues_t_test_achilles_new1vs3

pvalues_t_test_achilles_new1vs3<-dplyr::arrange(pvalues_t_test_achilles_new1vs3, p_value)
pvalues_t_test_achilles_new1vs3
```
```{r}
##1vs3
##extra dataframe for the report to show the solutions from the t.test at prism.achilles
pvalues_t_test_achilles_new1vs3_reduced<-pvalues_t_test_achilles_new1vs3[rownames(pvalues_t_test_achilles_new1vs3)%in% c("OR4C11","KLRK1","KRT36"),]
pvalues_t_test_achilles_new1vs3_reduced
```

```{r}
## looking at the genes from cluster 1 and 3 and doing a t-test
##prism.exp
reduced_prism_exp_ovarycellc1<- prism.exp[rownames(prism.exp) %in% achilles_vector_cluster1,]
reduced_prism_exp_ovarycellc3<- prism.exp[rownames(prism.exp) %in% achilles_vector_cluster3,]

##for each column df1 and df3 welch t-test (assuming anequal variance)
pvalues_t_test_exp_1vs3<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,reduced_prism_exp_ovarycellc1,reduced_prism_exp_ovarycellc3))

pvalues_t_test_exp_1vs3

##creatig a dataframe with p-vaues and genes
pvalues_t_test_exp_1vs3<-dplyr::rename(pvalues_t_test_exp_1vs3,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_exp_1vs3$Bonferroni <-
      p.adjust(pvalues_t_test_exp_1vs3$p_value,
               method = "bonferroni")

pvalues_t_test_exp_1vs3

pvalues_t_test_exp_1vs3<-dplyr::arrange(pvalues_t_test_exp_1vs3, p_value)
pvalues_t_test_exp_1vs3
```
```{r}
##1vs3
##extra dataframe for the report to show the solutions from the t.test at prism.exp
pvalues_t_test_exp_1vs3_reduced<-pvalues_t_test_exp_1vs3[rownames(pvalues_t_test_exp_1vs3)%in% c("UCHL1","UACA","BEX4"),]
pvalues_t_test_exp_1vs3_reduced
```


```{r}
## looking at the genes from cluster 1 and 3 and doing a t-test
##prism.cnv
reduced_prism_cnv_ovarycellc1<- prism.cnv[rownames(prism.cnv) %in% achilles_vector_cluster1,]
reduced_prism_cnv_ovarycellc3<- prism.cnv[rownames(prism.cnv) %in% achilles_vector_cluster3,]

##for each column df1 and df4 welch t-test (assuming anequal variance)
pvalues_t_test_cnv_1vs3<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,reduced_prism_cnv_ovarycellc1,reduced_prism_cnv_ovarycellc3))

pvalues_t_test_cnv_1vs3

##creatig a dataframe with p-vaues and genes
pvalues_t_test_cnv_1vs3<-dplyr::rename(pvalues_t_test_cnv_1vs3,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_cnv_1vs3$Bonferroni <-
      p.adjust(pvalues_t_test_cnv_1vs3$p_value,
               method = "bonferroni")

pvalues_t_test_cnv_1vs3

pvalues_t_test_cnv_1vs3<-dplyr::arrange(pvalues_t_test_cnv_1vs3, p_value)
pvalues_t_test_cnv_1vs3
```
```{r}
##1vs3
##extra dataframe for the report to show the solutions from the t.test at prism.cnv
pvalues_t_test_cnv_1vs3_reduced<-pvalues_t_test_cnv_1vs3[rownames(pvalues_t_test_cnv_1vs3)%in% c("OPHN1","YIPF6","STARD8"),]
pvalues_t_test_cnv_1vs3_reduced
```



```{r}
##trying cluster 1vs4
##important
## looking at one drug which is responding to those cluster differently between 1 and 4
##mean for cluster 1 and 4

mean_effective_ovary_new1
mean_effective_ovary_new4

##for each column df1 and df4 t-test
pvalues_t_test_treat4vs1<-data.frame(mapply(function(x,y)t.test(x,y,na.rm=TRUE,alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,mean_effective_ovary_new1,mean_effective_ovary_new4))
pvalues_t_test_treat4vs1

##creatig a dataframe with p-vaues and genes
pvalues_t_test_treat4vs1<-rename(pvalues_t_test_treat4vs1,p_value=mapply.function.x..y..t.test.x..y..na.rm...TRUE..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_treat4vs1$Bonferroni <-
      p.adjust(pvalues_t_test_treat4vs1$p_value,
               method = "bonferroni")


pvalues_t_test_treat4vs1

##ranking the drugs
pvalues_t_test_treat4vs1<-dplyr::arrange(pvalues_t_test_treat4vs1, Bonferroni)
pvalues_t_test_treat4vs1
```
```{r}
##1vs4
##extra dataframe for the report to show the solutions from the t.test at prism.treat
pvalues_t_test_treat4vs1_reduced<-pvalues_t_test_treat4vs1[rownames(pvalues_t_test_treat4vs1)%in% c("torin-1","AVN-944"),]
pvalues_t_test_treat4vs1_reduced
```


```{r}
## only those 3 drugs in one dataframe

selected_drug_ovary1<-select(mean_effective_ovary_new1, c("torin-1","AVN-944"))
selected_drug_ovary1
selected_drug_ovary4<-select(mean_effective_ovary_new4,c("torin-1","AVN-944"))
selected_drug_ovary4
```

```{r}
## looking at the genes from cluster 1 and 4 and doing a t-test

##for each column df1 and df4 welch t-test (assuming unequal variance)
pvalues_t_test_achilles_new1vs4<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,ovary_achilles_cluster1,ovary_achilles_cluster4))

pvalues_t_test_achilles_new1vs4

##creatig a dataframe with p-vaues and genes
pvalues_t_test_achilles_new1vs4<-dplyr::rename(pvalues_t_test_achilles_new1vs4,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_achilles_new1vs4$Bonferroni <-
      p.adjust(pvalues_t_test_achilles_new1vs4$p_value,
               method = "bonferroni")

pvalues_t_test_achilles_new1vs4

pvalues_t_test_achilles_new1vs4<-dplyr::arrange(pvalues_t_test_achilles_new1vs4, p_value)
pvalues_t_test_achilles_new1vs4
```
```{r}
##1vs4
##extra dataframe for the report to show the solutions from the t.test at prism.achilles
pvalues_t_test_achilles_new1vs4_reduced<-pvalues_t_test_achilles_new1vs4[rownames(pvalues_t_test_achilles_new1vs4)%in% c("SF3B5","TM4SF4","GINS4"),]
pvalues_t_test_achilles_new1vs4_reduced
```


```{r}
## looking at the genes from cluster 1 and 4 and doing a t-test
##prism.exp
reduced_prism_exp_ovarycellc1<- prism.exp[rownames(prism.exp) %in% achilles_vector_cluster1,]
reduced_prism_exp_ovarycellc4<- prism.exp[rownames(prism.exp) %in% achilles_vector_cluster4,]

##for each column df1 and df4 welch t-test (assuming anequal variance)
pvalues_t_test_exp_1vs4<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,reduced_prism_exp_ovarycellc1,reduced_prism_exp_ovarycellc4))

pvalues_t_test_exp_1vs4

##creatig a dataframe with p-vaues and genes
pvalues_t_test_exp_1vs4<-dplyr::rename(pvalues_t_test_exp_1vs4,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_exp_1vs4$Bonferroni <-
      p.adjust(pvalues_t_test_exp_1vs4$p_value,
               method = "bonferroni")

pvalues_t_test_exp_1vs4

pvalues_t_test_exp_1vs4<-dplyr::arrange(pvalues_t_test_exp_1vs4, p_value)
pvalues_t_test_exp_1vs4
```
```{r}
##1vs4
##extra dataframe for the report to show the solutions from the t.test at prism.exp
pvalues_t_test_exp_1vs4_reduced<-pvalues_t_test_exp_1vs4[rownames(pvalues_t_test_exp_1vs4)%in% c("KBTBD11","TSPAN33","ASPHD2"),]
pvalues_t_test_exp_1vs4_reduced
```

```{r}
## looking at the genes from cluster 1 and 4 and doing a t-test
##prism.cnv
reduced_prism_cnv_ovarycellc1<- prism.cnv[rownames(prism.cnv) %in% achilles_vector_cluster1,]
reduced_prism_cnv_ovarycellc4<- prism.cnv[rownames(prism.cnv) %in% achilles_vector_cluster4,]

##for each column df1 and df4 welch t-test (assuming anequal variance)
pvalues_t_test_cnv_1vs4<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,reduced_prism_cnv_ovarycellc1,reduced_prism_cnv_ovarycellc4))

pvalues_t_test_cnv_1vs4

##creatig a dataframe with p-vaues and genes
pvalues_t_test_cnv_1vs4<-dplyr::rename(pvalues_t_test_cnv_1vs4,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_cnv_1vs4$Bonferroni <-
      p.adjust(pvalues_t_test_cnv_1vs4$p_value,
               method = "bonferroni")

pvalues_t_test_cnv_1vs4

pvalues_t_test_cnv_1vs4<-dplyr::arrange(pvalues_t_test_cnv_1vs4, p_value)
pvalues_t_test_cnv_1vs4
```

```{r}
##1vs4
##extra dataframe for the report to show the solutions from the t.test at prism.cnv
pvalues_t_test_cnv_1vs4_reduced<-pvalues_t_test_cnv_1vs4[rownames(pvalues_t_test_cnv_1vs4)%in% c("LINC00842","ANTXRLP1","MIR1468"),]
pvalues_t_test_cnv_1vs4_reduced
```

```{r}
##cluster 2 and 4
mean_effective_ovary_new2= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary_new2[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovary_new2<-mean_effective_ovary_new2[rownames(mean_effective_ovary_new2) %in% achilles_vector_cluster2,]
mean_effective_ovary_new2

##prism.treat
pvalues_t_test_treat4vs2<-data.frame(mapply(function(x,y)t.test(x,y,na.rm=TRUE)$p.value,mean_effective_ovary_new2,mean_effective_ovary_new4))
pvalues_t_test_treat4vs2

##creatig a dataframe with p-vaues and genes
pvalues_t_test_treat4vs2<-rename(pvalues_t_test_treat4vs2,p_value=mapply.function.x..y..t.test.x..y..na.rm...TRUE..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_treat4vs2$Bonferroni <-
      p.adjust(pvalues_t_test_treat4vs2$p_value,
               method = "bonferroni")


pvalues_t_test_treat4vs2

##ranking the drugs
dplyr::arrange(pvalues_t_test_treat4vs2, Bonferroni)


## looking at the genes from cluster 2 and 4 and doing a t-test

##for each column df2 and df4 welch t-test (assuming anequal variance)
pvalues_t_test_achilles_new2vs4<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,ovary_achilles_cluster2,ovary_achilles_cluster4))

pvalues_t_test_achilles_new2vs4

##creatig a dataframe with p-vaues and genes
pvalues_t_test_achilles_new2vs4<-rename(pvalues_t_test_achilles_new2vs4,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_achilles_new2vs4$Bonferroni <-
      p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "bonferroni")

pvalues_t_test_achilles_new2vs4$BH <-
      p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "BH")

pvalues_t_test_achilles_new2vs4$Holm <-
        p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "holm")

pvalues_t_test_achilles_new2vs4$Hochberg <-
      p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "hochberg")

pvalues_t_test_achilles_new2vs4$Hommel <-
      p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "hommel")

pvalues_t_test_achilles_new2vs4$BY <-
      p.adjust(pvalues_t_test_achilles_new2vs4$p_value,
               method = "BY")


pvalues_t_test_achilles_new2vs4

dplyr::arrange(pvalues_t_test_achilles_new2vs4, p_value)
```


```{r}
##creating a dataframe from non ovary celllines out of cluster 2 and 4

##vector from cluster 2,4
achilles_vector_cluster24<- as.vector(c(achilles_vector_cluster2,achilles_vector_cluster4))

df_ovary_prism_treat_effective_longc2c4 <- df_ovary_prism_treat_effective_long [df_ovary_prism_treat_effective_long$DepMap_ID%in%achilles_vector_cluster24,]

df_ovary_treat_drugs<-pivot_wider(df_ovary_prism_treat_effective_longc2c4, names_from = DepMap_ID,values_from= proliferationvalues)
df_ovary_treat_drugs
##deleting every drug except for exatecan-mesylate, romidepsin and carfilzomib
##for ovary
df_ovary_prism_treat_effective_longc2c4erc <- df_ovary_prism_treat_effective_longc2c4 [df_ovary_prism_treat_effective_longc2c4$name%in%c("exatecan-mesylate","romidepsin","carfilzomib"),]
df_ovary_prism_treat_effective_longc2c4erc

##using pivot wider
df_ovary_prism_treat_effective_c2c4erc<-pivot_wider(df_ovary_prism_treat_effective_longc2c4, names_from = DepMap_ID,values_from= proliferationvalues)
df_ovary_prism_treat_effective_c2c4erc

##creating a dataframe from non ovary celllines out of cluster 2 and 4

##creating a vector from cluster 2 and 4
achilles_noovary_vector_cluster24<- as.vector(c(achilles_noovary_vector_cluster2, achilles_noovary_vector_cluster4))

df_noovary_prism_treat_effective_longc2c4 <- df_noovary_prism_treat_effective_long [df_noovary_prism_treat_effective_long$DepMap_ID%in%achilles_noovary_vector_cluster24,]
df_noovary_prism_treat_effective_longc2c4

df_noovary_treat_drugs<-pivot_wider(df_noovary_prism_treat_effective_longc2c4, names_from = DepMap_ID,values_from= proliferationvalues)
df_noovary_treat_drugs
##deleting every drug except for exatecan-mesylate, romidepsin and carfilzomib
##for non ovary
df_noovary_prism_treat_effective_longc2c4erc <- df_noovary_prism_treat_effective_longc2c4 [df_noovary_prism_treat_effective_longc2c4$name%in%c("exatecan-mesylate","romidepsin","carfilzomib"),]
df_noovary_prism_treat_effective_longc2c4erc

##using pivot wider
df_noovary_prism_treat_effective_c2c4erc<-pivot_wider(df_noovary_prism_treat_effective_longc2c4, names_from = DepMap_ID,values_from= proliferationvalues)
df_noovary_prism_treat_effective_c2c4erc

```

```{r, 1.2}
##creating a dataframe from the cellines out of cluster 2 and 4
##creating a ector for cluster k2moa 2 and 4
##ovary
achilles_vector_cluster2 = as.vector(na.omit(names(which(km2_moa$cluster == 2))))
achilles_vector_cluster2
achilles_vector_cluster4 = as.vector(na.omit(names(which(km2_moa$cluster == 4))))
achilles_vector_cluster4
##noovary
achilles_noovary_vector_cluster2 = as.vector(na.omit(names(which(km1_moa$cluster == 2))))
achilles_noovary_vector_cluster2
achilles_noovary_vector_cluster4 = as.vector(na.omit(names(which(km1_moa$cluster == 4))))
achilles_noovary_vector_cluster4


##creating a vector with both 
##ovary
achilles_vector_cluster24<- as.vector(c(achilles_vector_cluster2,achilles_vector_cluster4))
##noovary
achilles_noovary_vector_cluster24<- as.vector(c(achilles_noovary_vector_cluster2, achilles_noovary_vector_cluster4))


##reducing prism.achilles for the t.test to only the cluster 24 celllines
##ovary
ovary_achilles_cluster24 <- prism.achilles[rownames(prism.achilles) %in% achilles_vector_cluster24,]
ovary_achilles_cluster24
##nonovary
noovary_achilles_cluster24 <- prism.achilles[rownames(prism.achilles) %in% achilles_noovary_vector_cluster24,]
noovary_achilles_cluster24

 
```
```{r, 1.2}
## looking at one drug which is responding to those cluster differently
##mean for non ovary
mean_effective_noovary24= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_noovary24[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_noovary24<-mean_effective_noovary24[rownames(mean_effective_noovary24) %in% achilles_noovary_vector_cluster24,]
mean_effective_noovary24

##mean for ovary
mean_effective_ovary24= data.frame(row.names=rownames(prism))

for (drug in unique(prism.treat$name)){
  dose = prism.treat[prism.treat$name==drug,]$dose
  response = prism[,rownames(prism.treat)[prism.treat$name == drug]]
  
  mean_effective_ovary24[drug]=apply(response,1,function(x){mean(x, na.rm=TRUE)})
}
mean_effective_ovary24<-mean_effective_ovary24[rownames(mean_effective_ovary24) %in% achilles_vector_cluster24,]
mean_effective_ovary24

##for each column dfovary and dfnonovary t-test
pvalues_t_test_treat24<-data.frame(mapply(function(x,y)t.test(x,y,na.rm=TRUE,alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,mean_effective_ovary24,mean_effective_noovary24))
pvalues_t_test_treat24

##creatig a dataframe with p-values and drugs
pvalues_t_test_treat24<-rename(pvalues_t_test_treat24,p_value=mapply.function.x..y..t.test.x..y..na.rm...TRUE..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_treat24$Bonferroni <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "bonferroni")

pvalues_t_test_treat24$BH <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "BH")

pvalues_t_test_treat24$Holm <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "holm")

pvalues_t_test_treat24$Hochberg <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "hochberg")

pvalues_t_test_treat24$Hommel <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "hommel")

pvalues_t_test_treat24$BY <-
      p.adjust(pvalues_t_test_treat24$p_value,
               method = "BY")

pvalues_t_test_treat24

##ranking the drugs
dplyr::arrange(pvalues_t_test_treat24, Bonferroni)

####no significant differences between the drug response between ovary and non ovary celllines!
```
```{r}
##looking into TAK-733
selected_drug_ovary<-select(mean_effective_ovary24, "TAK-733")
selected_drug_ovary
selected_drug_noovary<-select(mean_effective_noovary24,"TAK-733")
selected_drug_noovary
```


```{r}
##t-test with ovary and nonovary

##for each column dfovary and dfnonovary welch t-test (assuming anequal variance)
pvalues_t_test_achilles24<-data.frame(mapply(function(x,y)t.test(x,y, alternative="two.sided", var.equal= FALSE, paired=FALSE)$p.value,ovary_achilles_cluster24,noovary_achilles_cluster24))

pvalues_t_test_achilles24

##creatig a dataframe with p-vaues and genes
pvalues_t_test_achilles24<-rename(pvalues_t_test_achilles24,p_value=mapply.function.x..y..t.test.x..y..alternative....two.sided...)

##adjusting the pvalue by all methods and creating a dataframe with new columns with those methods
pvalues_t_test_achilles24$Bonferroni <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "bonferroni")

pvalues_t_test_achilles24$BH <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "BH")

pvalues_t_test_achilles24$Holm <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "holm")

pvalues_t_test_achilles24$Hochberg <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "hochberg")

pvalues_t_test_achilles24$Hommel <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "hommel")

pvalues_t_test_achilles24$BY <-
      p.adjust(pvalues_t_test_achilles24$p_value,
               method = "BY")

pvalues_t_test_achilles24

##doing a plot for each column
X = pvalues_t_test_achilles24$p_value
Y = cbind(pvalues_t_test_achilles24$Bonferroni,
          pvalues_t_test_achilles24$BH,
          pvalues_t_test_achilles24$Holm,
          pvalues_t_test_achilles24$Hochberg,
          pvalues_t_test_achilles24$Hommel,
          pvalues_t_test_achilles24$BY)

matplot(X, Y,
        xlab="Raw p-value",
        ylab="Adjusted p-value",
        type="l",
        asp=1,
        col=1:6,
        lty=1,
        lwd=2)

legend('bottomright',
       legend = c("Bonferroni", "BH", "Holm", "Hochberg", "Hommel", "BY"),
       col = 1:6,
       cex = 1,   
       pch = 16)

abline(0, 1,
       col=1,
       lty=2,
       lwd=1)

```
```{r}
##ranking the genes
dplyr::arrange(pvalues_t_test_achilles24, Bonferroni)

##Therefore, the smaller the p-value, the stronger the evidence is that the two populations have different means.

##creating a reduced dataframe with only the 6 genes with the most difference between the meanvalues and the lowest t-test.
vector_genes_difference<-as.vector(c("IGF1R","OR2V2","WNK1"))


reduced_ovary_achilles_genes<-select(ovary_achilles_cluster24,vector_genes_difference)
reduced_ovary_achilles_genes

reduced_noovary_achilles_genes<-select(noovary_achilles_cluster24,vector_genes_difference)
reduced_noovary_achilles_genes

hist(reduced_ovary_achilles_genes$IGF1R)
hist(reduced_noovary_achilles_genes$IGF1R)

hist(reduced_ovary_achilles_genes$OR2V2)
hist(reduced_noovary_achilles_genes$OR2V2)

hist(reduced_ovary_achilles_genes$WNK1)
hist(reduced_noovary_achilles_genes$WNK1)
```

```{r}
## correlation between drug and genes

```

```{r}

##starting with prism exp
##reducing prism.exp to the cluster 13 and the 20 genes
##ovary
reduced_prism_exp_ovarycell<- prism.exp[rownames(prism.exp) %in% achilles_vector_cluster24,]
reduced_prism_exp_ovary<-select(reduced_prism_exp_ovarycell,vector_genes_difference)
reduced_prism_exp_ovary

prism_cnv_BCRA1_KRAS_BCRA2<-select(reduced_prism_exp_ovarycell,c(BRCA1,BRCA2,KRAS))
prism_cnv_BCRA1_KRAS_BCRA2

##noovary
reduced_prism_exp_noovarycell<- prism.exp[rownames(prism.exp) %in% achilles_noovary_vector_cluster24,]
reduced_prism_exp_noovary<-select(reduced_prism_exp_noovarycell,vector_genes_difference)
reduced_prism_exp_noovary

prism_cnv_BCRA1_KRAS_BCRA2<-select(reduced_prism_exp_noovarycell,c(BRCA1,BRCA2,KRAS))
prism_cnv_BCRA1_KRAS_BCRA2
##higher values say over expression lesser values means lower expression

```
```{r}

```


```{r}
##prism.cnv copy number from the genes
#ovary
reduced_prism_cnv_ovarycell<- prism.cnv[rownames(prism.cnv) %in% achilles_vector_cluster24,]
reduced_prism_cnv_ovary<-select(reduced_prism_cnv_ovarycell,vector_genes_difference)
reduced_prism_cnv_ovary

prism_cnv_BCRA1_KRAS_BCRA2<-select(reduced_prism_cnv_ovarycell,c(BRCA1,BRCA2,KRAS))
prism_cnv_BCRA1_KRAS_BCRA2
                                   
#noovary
reduced_prism_cnv_noovarycell<- prism.cnv[rownames(prism.cnv) %in% achilles_noovary_vector_cluster24,]
reduced_prism_cnv_noovary<-select(reduced_prism_cnv_noovarycell,vector_genes_difference)
reduced_prism_cnv_noovary

prism_cnv_BCRA1_KRAS_BCRA2<-select(reduced_prism_cnv_noovarycell,c(BRCA1,BRCA2,KRAS))
prism_cnv_BCRA1_KRAS_BCRA2

```
```{r}

```

